name: Build and Analyze with SonarQube

on:
  push:
    branches:
      - main


jobs:
  build:
    name: Build and Analyze
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure a full clone for better analysis relevancy

      # Step 2: Set up Java (required for SonarScanner)
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: 17  # Ensure Java 17 is available
          distribution: 'temurin'  # Use Eclipse Temurin for compatibility
      # Step 3: Download the Servlet API JAR
      - name: Download javax.servlet-api JAR
        run: |
          curl -L -o javax.servlet-api-4.0.1.jar https://repo1.maven.org/maven2/javax/servlet/javax.servlet-api/4.0.1/javax.servlet-api-4.0.1.jar
          mkdir -p lib && mv javax.servlet-api-4.0.1.jar lib/

      # Step 4: Compile Java files
      - name: Compile Java files
        run: |
          mkdir -p out
          javac -cp lib/javax.servlet-api-4.0.1.jar  $(find . -name "*.java")

      # Step 5: Run Java program (if applicable)
      - name: Run Java program
        run: |
          java -cp lib/javax.servlet-api-4.0.1.jar: *

      # Step 3: Install Python dependencies (optional, for Python projects)
      - name: Install Python dependencies
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Adjust to your project's Python version
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Ensure requirements.txt exists

      # Step 4: Run SonarQube scan
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v3
        env:
          SONAR_TOKEN: sqp_d991f256fabfcc46e0f8fa28812f87766e24395c  # Token from SonarQube
          SONAR_HOST_URL: http://localhost:9000  # SonarQube URL
          SONAR_PROJECT_KEY: ASSS_project  # Replace with your project's SonarQube key
          SONAR_LOGIN: ${{ secrets.SONAR_USERNAME }}  # Username from GitHub Secrets
          SONAR_PASSWORD: ${{ secrets.SONAR_PASSWORD }}  # Password from GitHub Sec
      # Optional Step 5: Check SonarQube Quality Gate Status
  