name: Python SonarQube Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarqube:
    name: Run SonarQube Analysis
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.13'  # Use the Python version your project requires

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Ensure you have a requirements.txt file

      # Step 4: Run SonarQube analysis
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v3
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # Make sure you have the SONAR_TOKEN set in GitHub Secrets
          SONAR_HOST_URL:  ${{ secrets.SONAR_HOST_URL }}# Replace with your SonarQube instance URL
          SONAR_PROJECT_KEY: ASSS_project  # Replace with your SonarQube project key

      # Optional: Step 5 to Check if the SonarQube Quality Gate passes
      - name: Check quality gate
        uses: sonarsource/sonarqube-quality-gate-action@v1
        with:
          sonar-token: ${{ secrets.SONAR_TOKEN }}
        env:
          SONAR_HOST_URL: https://your-sonarqube-instance-url  # Replace with your SonarQube instance URL
